### ISSUE TITLE
Cannot read properties of null (reading 'url')

### ISSUE THREAD

**Issue by jdenisgiguere** [jakarto3d/widget_jakartowns_wab#1]
Lorsque l'on essaie d'utiliser le widget, on obtient le message d'erreur suivant:

> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'url')
>     at Object.getDDPoint (Widget.js?wab_dv=2.21:74:27)
>     at Object._onDrawEnd (Widget.js?wab_dv=2.21:58:35)
>     at Object.<anonymous> (init.js:65:128)
>     at Object.e [as onDrawEnd] (init.js:121:484)
>     at Object._onDrawEnd (DrawBox.js?wab_dv=2.21:503:12)
>     at Object.<anonymous> (init.js:65:128)
>     at Object.<anonymous> (init.js:692:63)
>     at Object.e [as onDrawEnd] (init.js:121:484)

https://github.com/jakarto3d/widget_jakartowns_wab/blob/bedd2d35d0abaf3f94c24eeb5966fcf480867203/Jakartowns/Widget.js#L74

Ce n'est pas trivial pour moi où devrait être initialisé `this._gs`.

**Comment by jdenisgiguere** [comment]
Cette erreur se présentera seulement lorsqu'il faut faire des conversions entre des systèmes de référence spatiale non-supportés par https://developers.arcgis.com/javascript/latest/api-reference/esri-geometry-support-webMercatorUtils.html .

Comme Web AppBuilder est en fin de vie, nous ne corrigerons pas l'anomalie.
